### PR TITLE
Task set up

### LINKED ISSUE #37: AAU - I want to be able to complete a level
Abstract:

Be able to complete certain tasks which then leads to the completion of a level

Requirements:

- Integration w/ a Level Manager to get it informed about task completion
- Make a station prefab that'll be the base template for making a task station
- As a player, I should be able to make some, but very little progress toward tasks
- Integrate humans into level completion in some form
- Does not need any special notice to show that a level has been completed, even a debug log is fine

### PR DESCRIPTION
**Pull request by EdwardLe0n**
Using interactable templates as a base, made a station for players and humans to work at

General list:
- Both players and humans can work at stations
- Players need to constantly spam the interact button to do anything, humans passively work on tasks
- Integrated task completion with a level manager so that a higher system is informed about level completion
- Modified the level 1 scene as an example

### CODE REVIEW

**Review by ColtonKor — APPROVED** [review]
TASK

**Review by mbelles21 — APPROVED** [review]
ok

**Review by mbelles21 — APPROVED** [review]
ok 2

**Review by mbelles21 — APPROVED** [review]
ok 3

**Review by Af0n — APPROVED** [review]
I. LOVE. GITHUB GITHUB MERGE RUUULES!!!

**Review by ColtonKor — APPROVED** [review]
It is goooooood

**Pull request merged**
